version: '3.12'
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest 
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      #Rabbit instance
      - '5672:5672'
      #web interface
      - '15672:15672'
